version: '3.8'
services:
  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/invoicing
    depends_on:
      - mongodb
    volumes:
      - ./back-end:/app
    command: ["npm", "start"]

  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
    depends_on:
      - backend
    command: ["npm", "start"]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: