services:
  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/invoicing
      - NODE_ENV=production
    depends_on:
      - mongodb

  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: invoicer
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: